[package]
name = "decrypt-cookies"
version = "0.6.0"
description = "A decrypt browser crate"
license = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
# homepage     = { workspace = true }
homepage = "https://github.com/saying121/tidy-browser/tree/master/crates/decrypt-cookies"
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
rust-version = { workspace = true }

exclude = ["tests/", "examples"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
miette = { workspace = true }
rayon = { workspace = true }
chrono = { workspace = true }

sea-orm = { workspace = true }

tracing = { workspace = true }

serde = { workspace = true }

rust-ini = { workspace = true } # firefox

dirs = { workspace = true }

cfg-if = { workspace = true }

strum = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, default-features = false, features = [
  "cookies",
], optional = true }

[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "openbsd"))'.dependencies]
secret-service = { workspace = true, default-features = true, features = [
  "rt-tokio-crypto-rust",
] }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
bytes = { workspace = true }
keyring = { workspace = true, default-features = false, features = [
  "apple-native",
] } # It is not working as expected on Linux.

[target.'cfg(not(windows))'.dependencies]
aes = { workspace = true }
cbc = { workspace = true }
pbkdf2 = { workspace = true, features = ["sha1"] }
sha1 = { workspace = true }

[target.'cfg(windows)'.dependencies]
aes-gcm = { workspace = true }
base64 = { workspace = true }
serde_json = { workspace = true }
windows = { workspace = true, features = [
  "Win32_Security_Cryptography",
  # "Win32_Foundation",
  # "Win32_System",
  # "Win32_System_RestartManager",
] }

[dev-dependencies]
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
miette = { workspace = true, features = ["fancy"] }
reqwest = { workspace = true, features = ["cookies"] }

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest"]

[lints]
workspace = true
