[package]
name        = "decrypt-cookies"
version     = "0.1.8"
description = "A decrypt browser cookies crate"
license     = "LGPL-3.0-or-later"
edition     = { workspace = true }
authors     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }

exclude = ["tests/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio  = { version = "^1" }
miette = { workspace = true }

sea-orm = { workspace = true }

tracing = { workspace = true }

serde    = { workspace = true }
rust-ini = { version = "0.21" }

dirs = { workspace = true }

strum        = { version = "^0.26" }
strum_macros = { version = "^0.26" }

aes = { version = "0.8.3" }

[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "openbsd"))'.dependencies]
secret-service = { version = "^3", default_features = true, features = ["rt-tokio-crypto-rust"] }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
# It is not working as expected on Linux.
keyring = { version = "^2", default_features = false, features = ["platform-macos"] }

[target.'cfg(not(windows))'.dependencies]
cbc    = { version = "0.1.2" }
pbkdf2 = { version = "0.12.2", features = ["sha1"] }
sha1   = { version = "0.10.6" }

[target.'cfg(windows)'.dependencies]
serde_json = { version = "^1" }
base64 = { version = "^0.22" }
windows = { version = "^0.54", features = [
    "Win32_Security_Cryptography",
    "Win32_Foundation",
    "Win32_System",
    "Win32_System_RestartManager",
] }
aes-gcm = { version = "^0.10" }

[dev-dependencies]
tracing-subscriber = { workspace = true }
tokio              = { version = "^1", features = ["macros", "rt-multi-thread"] }
miette             = { workspace = true, features = ['fancy'] }

[lints]
workspace = true
