[package]
name = "decrypt-cookies"
version = "0.7.0-alpha.0"
description = "A decrypt browser crate"
license = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
# homepage     = { workspace = true }
homepage = "https://github.com/saying121/tidy-browser/tree/master/crates/decrypt-cookies"
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
rust-version = { workspace = true }

exclude = ["tests/", "examples", "./CHANGELOG.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }
chrono = { workspace = true }

sea-orm = { workspace = true }

tracing = { workspace = true }

serde = { workspace = true }

rust-ini = { workspace = true } # firefox

dirs = { workspace = true }

reqwest = { workspace = true, default-features = false, features = ["cookies"], optional = true }

[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "openbsd"))'.dependencies]
secret-service = { workspace = true, default-features = true, features = ["rt-tokio-crypto-rust"] }

[target.'cfg(not(any(target_os = "macos", target_os = "ios")))'.dependencies]
bytes = { workspace = true, optional = true }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
bytes = { workspace = true }
keyring = { workspace = true, default-features = false, features = [
    "apple-native",
] } # It is not working as expected on Linux.

[target.'cfg(not(windows))'.dependencies]
aes = { workspace = true }
cbc = { workspace = true }
pbkdf2 = { workspace = true, features = ["sha1"] }
sha1 = { workspace = true }
const_format = { workspace = true }

[target.'cfg(windows)'.dependencies]
aes-gcm = { workspace = true }
base64 = { workspace = true }
serde_json = { workspace = true }
windows = { workspace = true, features = ["Win32_Security_Cryptography"] }

[dev-dependencies]
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
anyhow = { workspace = true }
reqwest = { workspace = true, features = ["cookies"] }

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest"]
binary_cookies = ["dep:bytes"] # `binary_cookies` does not depend on Macos

[lints]
workspace = true
