[package]
name         = "decrypt-cookies"
version      = "0.5.2"
description  = "A decrypt browser crate"
license      = "LGPL-3.0-or-later"
edition      = { workspace = true }
authors      = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
keywords     = ["cookies", "decrypt", "Chromium", "Firefox", "Safari"]
categories   = ["asynchronous", "authentication", "cryptography", "encoding"]
rust-version = "1.77"

exclude = ["tests/", "examples"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio  = { workspace = true }
miette = { workspace = true }
rayon  = { version = "^1" }
chrono = { version = "^0.4" }

sea-orm = { workspace = true }

tracing = { workspace = true }

serde = { workspace = true }

rust-ini = { version = "0.21" } # firefox

dirs = { workspace = true }

cfg-if = { version = "^1" }

strum        = { workspace = true }
strum_macros = { version = "^0.26" }

[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "openbsd"))'.dependencies]
secret-service = { version = "^3", default_features = true, features = ["rt-tokio-crypto-rust"] }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
bytes = { version = "^1" }
keyring = { version = "^2", default_features = false, features = [
    "platform-macos",
    "platform-ios",
] } # It is not working as expected on Linux.

[target.'cfg(not(windows))'.dependencies]
aes    = { version = "0.8.3" }
cbc    = { version = "0.1.2" }
pbkdf2 = { version = "0.12.2", features = ["sha1"] }
sha1   = { version = "0.10.6" }

[target.'cfg(windows)'.dependencies]
aes-gcm    = { version = "^0.10" }
base64     = { version = "^0.22" }
serde_json = { version = "^1" }
windows = { version = "^0.54", features = [
    "Win32_Security_Cryptography",
    # "Win32_Foundation",
    # "Win32_System",
    # "Win32_System_RestartManager",
] }

[dev-dependencies]
tracing-subscriber = { workspace = true }
tokio              = { version = "^1", features = ["macros", "rt-multi-thread"] }
miette             = { workspace = true, features = ['fancy'] }

[lints]
workspace = true
