//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cookies")]
pub struct Model {
    pub creation_utc: i64,
    #[sea_orm(column_type = "Text")]
    pub host_key: String,
    #[sea_orm(column_type = "Text")]
    pub top_frame_site_key: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub value: String,
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_type = "Blob")]
    pub encrypted_value: Vec<u8>,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    pub expires_utc: i64,
    pub is_secure: i32,
    pub is_httponly: i32,
    pub last_access_utc: i64,
    pub has_expires: i32,
    pub is_persistent: i32,
    pub priority: i32,
    pub samesite: i32,
    pub source_scheme: i32,
    pub source_port: i32,
    pub last_update_utc: i64,
    // pub source_type:             i32,
    // pub has_cross_site_ancestor: i32,
    // pub is_edgelegacycookie: i32,
    // pub browser_provenance:      i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
