//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "insecure_credentials")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub parent_id:                         i32,
    pub insecurity_type:                   i32,
    pub create_time:                       i64,
    pub is_muted:                          i32,
    pub trigger_notification_from_backend: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::logins::Entity",
        from = "Column::ParentId",
        to = "super::logins::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Logins,
}

impl Related<super::logins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Logins.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
