//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "meta")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "custom(\"LONGVARCHAR\")"
    )]
    pub key: String,
    #[sea_orm(column_type = "custom(\"LONGVARCHAR\")", nullable)]
    pub value: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
