//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod insecure_credentials;
pub mod logins;
pub mod logins_edge_extended;
pub mod meta;
pub mod password_notes;
pub mod stats;
pub mod sync_entities_metadata;
pub mod sync_model_metadata;
