//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
#![expect(unused_imports, reason = "bindgen code")]

pub use super::{
    insecure_credentials::Entity as InsecureCredentials, logins::Entity as Logins,
    logins_edge_extended::Entity as LoginsEdgeExtended, meta::Entity as Meta,
    password_notes::Entity as PasswordNotes, stats::Entity as Stats,
    sync_entities_metadata::Entity as SyncEntitiesMetadata,
    sync_model_metadata::Entity as SyncModelMetadata,
};
