[package]
name        = "tidy-browser"
version     = "0.1.0"
description = "tidy up browser information."
license     = "LGPL-3.0-or-later"
edition     = { workspace = true }
authors     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }


[dependencies]
tokio              = { workspace = true, features = ["rt-multi-thread", "macros", "tracing"] }
clap               = { version = "^4" }
miette             = { workspace = true, features = ["fancy"] }
decrypt-cookies    = { workspace = true }
strum              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
