[package]
name = "binary-cookies"
version = "0.1.0"
description = "BinaryCookies decode and encode"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "./README.md"
exclude  = ["test-resource/"]

[dependencies]
oval = { workspace = true }
winnow = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
annotate-snippets = { workspace = true }
bstr = { workspace = true }
plist = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
test-with = { workspace = true }
const_format = { workspace = true }
pretty_assertions = { workspace = true }

[lints]
workspace = true
