name: Clippy

on: [push, pull_request, merge_group]

env:
  RUST_BACKTRACE: 1

jobs:
  clippy:
    name: Clippy rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout/@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy Allow Warning
        if: ${{ ! (github.ref == 'refs/heads/master' || github.event_name == 'pull_request') }}
        run: cargo clippy --locked

      - name: Run Clippy Deny Warning
        if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
        run: cargo clippy --locked -- -D warnings
