name: Clippy

on: [push, pull_request, merge_group]

env:
  RUST_BACKTRACE: 1

jobs:
  clippy:
    name: Clippy rust
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout/@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy Deny Warning
        run: cargo clippy --tests --locked -- -D warnings
