name: Clippy

on: [push]

env:
  RUST_BACKTRACE: 1

jobs:
  clippy:
    name: Clippy rust
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - uses: actions/checkout/@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.82

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: '0.10.0'

      - name: Run Clippy Deny Warning
        run: cargo clippy --tests --locked -- -D warnings
