name: Rustfmt

on:
  push:
    paths-ignore:
      - "./**/*.md"

permissions:
  contents: write

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          # my rustfmt config use many nightly features
          toolchain: nightly
          components: rustfmt, cargo
      - name: Run Fmt Check
        run: cargo x fmt -- --check
